// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBQHh3-wcQLCNAi5a2AvCea09xiXh0sVUU',
    appId: '1:1021458228463:web:02d0c5126360e0a74da71a',
    messagingSenderId: '1021458228463',
    projectId: 'alamiyah',
    authDomain: 'alamiyah.firebaseapp.com',
    storageBucket: 'alamiyah.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyASXizCHJeLYd2qJkBP94bmXJ8T8KknRYM',
    appId: '1:1021458228463:android:6d0173708acbeb974da71a',
    messagingSenderId: '1021458228463',
    projectId: 'alamiyah',
    storageBucket: 'alamiyah.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBKpPjKoomOuAHoYamu9vkRb0b6sX_w5EE',
    appId: '1:1021458228463:ios:344b40fa80215a274da71a',
    messagingSenderId: '1021458228463',
    projectId: 'alamiyah',
    storageBucket: 'alamiyah.firebasestorage.app',
    iosBundleId: 'com.alamiyah.alamiyah',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBQHh3-wcQLCNAi5a2AvCea09xiXh0sVUU',
    appId: '1:1021458228463:web:02d0c5126360e0a74da71a',
    messagingSenderId: '1021458228463',
    projectId: 'alamiyah',
    authDomain: 'alamiyah.firebaseapp.com',
    storageBucket: 'alamiyah.firebasestorage.app',
  );
}
